let valid = {

    'abbr': true,
    'acronym': true,
    'address': true,
    'applet': true,
    'area': true,
    'article': true,
    'aside': true,
    'audio': true,
    'base': true,
    'basefont': true,
    'bdi': true,
    'bdo': true,
    'br': true,
    'canvas': true,
    'caption': true,
    'center': true,
    'col': true,
    'colgroup': true,
    'details': true,
    'dfn': true,
    'dialog': true,
    'dir': true,
    'dl': true,
    'dt': true,
    'embed': true,
    'fieldset': true,
    'figcaption': true,
    'font': true,
    'footer': true,
    'form': true,
    'frame': true,
    'frameset': true,
    'h3': true,
    'h4': true,
    'h5': true,
    'h6': true,
    'head': true,
    'hader': true,
    'img': true,
    'input': true,
    'keygen': true,
    'li': true,
    'link': true,
    'main': true,
    'map': true,
    'mark': true,
    'menu': true,
    'menuitem': true,
    'meta': true,
    'meter': true,
    'nav': true,
    'noframes': true,
    'noscript': true,
    'object': true,
    'ol': true,
    'option': true,
    'output': true,
    'param': true,
    'pre': true,
    'progress': true,
    'q': true,
    'rp': true,
    'rt': true,
    'ruby': true,
    'script': true,
    'section': true,
    'select': true,
    'small': true,
    'source': true,
    'strike': true,
    'strong': true,
    'style': true,
    'sub': true,
    'summary': true,
    'sup': true,
    'table': true,
    'tbody': true,
    'td': true,
    'textarea': true,
    'tfoot': true,
    'th': true,
    'thread': true,
    'time': true,
    'title': true,
    'tr': true,
    'track': true,
    'tt': true,
    'u': true,
    'ul': true,
    'var': true,
    'video': true,
    'wbr': true,
    'web-component': true,

    // SVG

    'animate': true,
    'animateColor': true,
    'animateMotion': true,
    'circle': true,
    'clipPath': true,
    'color-profile': true,
    'cursor': true,
    'defs': true,
    'ellipse': true,
    'filter': true,
    'font': true,
    'font-face': true,
    'g': true,
    'glyph': true,
    'glyphRef': true,
    'line': true,
    'linearGradient': true,
    'marker': true,
    'mask': true,
    'path': true,
    'pattern': true,
    'polygon': true,
    'polyline': true,
    'radialGradient': true,
    'rect': true,
    'stop': true,
    'svg': true,
    'switch': true,
    'symbol': true,
    'text': true,
    'textPath': true,
    'title': true,
    'tref': true,
    'tspan': true
};

function validtags(tag) {
    switch (tag) {
        case 'a':
        case 'button':
        case 'div':
        case 'em':
        case 'form':
        case 'img':
        case 'h1':
        case 'h2':
        case 'li':
        case 'ol':
        case 'p':
        case 'span':
        case 'table':
        case 'ul':
        case 'svg':
            return true;
        default:

            return valid[tag] ? true : false;
    }
};

export default validtags;